DATASETS:
  TRAIN:
    H36M-TRAIN:
      WEIGHT: 0.5
    COCO-TRAIN:
      WEIGHT: 0.3
    MPI-INF-TRAIN:
      WEIGHT: 0.2
  VAL:
    H36M-VAL-P2:
      WEIGHT: 0.5
    COCO-VAL:
      WEIGHT: 0.5
SMPL:
  MODEL_PATH: data/smpl
  GENDER: neutral
  NUM_BODY_JOINTS: 23
  JOINT_REGRESSOR_EXTRA: data/SMPL_to_J19.pkl
  MEAN_PARAMS: data/smpl_mean_params.npz
TRAIN:
  LR: 1e-4
  BATCH_SIZE: 128
  BATCH_SIZE_VAL: 64
  NUM_WORKERS: 8
  TOTAL_STEPS: 1000000
  LOG_FREQ: 10000
  CHECKPOINT_FREQ: 100000
  NUM_TRAIN_SAMPLES: 1
  NUM_VAL_SAMPLES: 4
  SAMPLE_START: 999
  DDIM_STEP_SIZE: 50
MODEL:
  IMG_SIZE: 224
  USE_BETAS: FALSE
  BETAS_STATS: data/stats/betas_stats_eft_fits.npz
  DIFFUSION_PROCESS:
    TIMESTEPS: 1000
    BETA_SCHEDULE: cosine
  DENOISING_MODEL:
    IMG_FEATS: pare
    POSE_DIM : 144
    SHAPE_DIM : 10
    NUM_BLOCKS_POSE: 3
    NUM_BLOCKS_SHAPE: 2
    HIDDEN_LAYER_DIM: 1024
    OBJECTIVE: pred_noise
    LOSS_TYPE: l2
GUIDANCE:
  OPTIM_ITERS: 10
  SAMPLE_START: 50
  DDIM_STEP_SIZE: 2
  GRADIENT_SCALE: 1.
  W_KP2D: 0.003
  W_MULTIVIEW: 0.005
  W_SMOOTH: 30
  USE_HIPS: True
EXTRA:
  PELVIS_IND: 39
  FOCAL_LENGTH: 5000
  LOAD_IMG_FEATS: None
  LOAD_PREDICTIONS: None